### ISSUE TITLE
`Inferior/Superior Limit` to `Lower/Upper bound`

### ISSUE THREAD

**Issue by ovari** [carlos157oliveira/Calculus#16]
1. Should `Inferior Limit` be `Lower bound`?
2. Should `Superior Limit` be `Upper bound`?

What do you think?

Thank you

**Comment by ovari** [comment]
Any reason why you don't add improvements to [Plots](https://flathub.org/apps/details/com.github.alexhuntley.Plots) and [Qalculate!](https://flathub.org/apps/details/io.github.Qalculate.qalculate-qt) instead of creating another similar program? Thank you

**Comment by carlos157oliveira** [comment]
This program was for a interdisciplinary project in my college. I found it cool to publish it on Flathub but I am aware it offers little (specially when you compare it). Currently I don't have time to support it and may deprecate.
About your suggestions: since my english isn't that nice, the phrases look the same for me. Would you mind to detail what would be the difference?

**Comment by ovari** [comment]
It is understood that the correct English terms for the integrand bounds are `Lower bound` and `Upper bound`.

Inferior and superior seems to imply that the inferior is always less than superior; however, the integrand can have values were the value of the lower bound is greater than the value of the upper bound.

Hope this helps and thank you for publishing your project of Flathub.

**Comment by carlos157oliveira** [comment]
What I have to say about this topic is disappointing... the limits are for the window that displays the graphic of the solution, the program works only with indefinite integrals with the integration constant being ignored. In another words, they define the interval for the plot and don't concern directly the integration operation.

**Comment by ovari** [comment]
Closing as a misunderstanding on our side on what the strings referred to. Sorry.
