### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kd2flz** [carlos157oliveira/Calculus#3]
Hi. This looks like a great little application! I was so pleased to stumble on it. However, I'm really not sure how to get started using it (what to put in which field). It would be cool if there was even some super basic documentation/ screenshots for example showing how to use it to find the derivative of a function.

Thanks so much, and good work. Also, kudos for releasing it as a flatpak.

**Comment by carlos157oliveira** [comment]
You are right, it definitely needs some documentation. I am thinking in creating a github page to explain the functionalities.

**Comment by kd2flz** [comment]
Cool, that would be perfect!
________________________________

**Comment by kd2flz** [comment]
First of all, that is a good overview of the program. There are some minor stylistic and grammatical changes it could use. As I have time, I might submit a pull request with some fixes. However, overall, it is looking good.

**Comment by carlos157oliveira** [comment]
Thank you for the feedback. I hope anyone who stumbles on the application will be able to understand the workflow now.

**Comment by carlos157oliveira** [comment]
Now the app flathub page (specifically the button *website*) points to the newly created documentation page. Feel free to still submit your pull request to the documentation page or even open another issue to ask anything. I am closing this issue since the principal problem seems to be effectively addressed.
