### ISSUE TITLE
Long expressions are truncated

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#8]
1. Enter the expression `x^x^x^x` 
1. Set the operation variable to `x`, 
1. Click Differentiate 
1. And then click Operate.

The resulting expression is not presented completely because the right hand side is truncated. This happens even when we make the Calculus window wider.

![Screenshot from 2020-11-18 18-43-42](https://user-images.githubusercontent.com/8484427/99614289-0b07e280-29ce-11eb-8d0a-649b9208ae2f.png)

I'm running Pop!\_OS 20.10 and installed Calculus 1.3.3 from the Pop Shop as a flatpak.

**Comment by carlos157oliveira** [comment]
Thank you for reporting! I have seen two distinct ways to address this:

1. The image width could be based on the current window size: the disadvantage is that resizing the window wouldn't work alone, the user would have to _Operate_ again after resizing the window;
2. A Settings menu could have an option to tweak the image size to the user tastes;

The problem is the image must have a size when it is produced, I haven't found an option that worked for adjusting matplotlib images to an text inside. There are other ways too:

3. If full LaTeX support is included then the resulting image with a text may be produced in other ways than through matplotlib, however the texlive extension would make the application much bigger;
4. Make it possible to open the result with an external program (an image viewer).

**Comment by johnblommers** [comment]
There is nothing wrong with the user widening the window to accommodate a wide image. Even if the Operate button must  be pressed. If the image is still too wide then it's good to give the user an option to open the image in an external image viewer. Or to save the image in PNG or SVG format.

**Comment by carlos157oliveira** [comment]
I found a way of considering the text size. I am publishing a new release to Flathub. Please, upgrade your version and tell me if it is also fixed for you.

**Comment by johnblommers** [comment]
Sure enough the newly updated Calculus fixes this problem. Sweet! Take a close look at the right hand side of the formula below, It looks like it's off by a pixel at the closing parenthesis:

![Screenshot from 2020-11-20 13-33-34](https://user-images.githubusercontent.com/8484427/99852140-3a852f00-2b35-11eb-8e98-4ec2470fdf12.png)

**Comment by carlos157oliveira** [comment]
For some reason, the size matplotlib calculates for the text gets underestimated for larger sizes. I had added a constant factor to fix this. Now it will be a variable factor since the bug keeps showing the larger we make the image. Please, upgrade and give me feedback, a new release will be soon available.

**Comment by johnblommers** [comment]
This latest version 1.3.5 resolves the truncation issue. Indeed Calculus will widen its window sufficiently regardless of how much real estate that requires. Even if that means widening the window beyond the screen's maximum horizontal resolution. That's perfect.

What I did not appreciate is that, under GNOME, even if a window is partially off-screen, <kbd>Alt</kbd><kbd>PrtSc</kbd> will capture all of it. Sweet!

This resolves the issue.

**Comment by carlos157oliveira** [comment]
Thank you, it was a lot of help. Feel free to open another issue for anything.
